### ISSUE TITLE
"SKYContainer has no member auth" when enabling chat extension

### ISSUE THREAD

**Issue by mayyuen318** [SkygearIO/skygear-Scaffolding-iOS#13] opened 2017-10-18 11:56 UTC
I was trying to run the scaffolding and I encounter the following error. 

<img width="1254" alt="screen shot 2017-10-18 at 7 13 33 pm" src="https://user-images.githubusercontent.com/7130966/31717338-1503ec38-b43e-11e7-826a-dbcf522aeec5.png">

**Comment by cheungpat** [comment] 2017-10-19 00:32
Hi, I understand that you are having problem using the scaffolding and I can reproduce the same errors. This is caused by the Chat iOS SDK [having a dependency on the 0.21.0 of the Skygear SDK](https://github.com/CocoaPods/Specs/blob/master/Specs/8/3/a/SKYKitChat/0.0.2/SKYKitChat.podspec.json).

This issue will be fixed when we have a new released version of the Chat SDK. Let me opens separate issues for that.

**Comment by cheungpat** [comment] 2017-10-19 00:41
Pending for https://github.com/SkygearIO/chat-SDK-iOS/issues/88

**Comment by chpapa** [comment] 2017-10-20 10:29
Should be okay now?

**Comment by mayyuen318** [comment] 2017-10-22 15:44
Yes. I worked now!

**Closed as completed** 2017-10-22 15:44 UTC
